resultados_digitais:
  client_id: 3MVG9fMtCkV6eLhfuUdE1a6QzjFHmmH8jXDowDY9YSuQzkjlrDA4rN3dLXKc7h_MoPFCM42a1i_4txPZG6_UT
  client_secret: 7695682468041596573
  username: thiagovs05@gmail.com
  password: testerdstation2014eQkoryOA5HQsthVOY6xRUaDbe

company_2:
  client_id: 3MVG9fMtCkV6eLhfuUdE1a6QzjFHmmH8jXDowDY9YSuQzkjlrDA4rN3dLXKc7h_MoPFCM42a1i_4txPZG6_UT
  client_secret: 7695682468041596573
  username: thiagovs05@gmail.com
  password: testerdstation2014eQkoryOA5HQsthVOY6xRUaDbe